FROM node:18 as build-stage
WORKDIR /app
COPY . /app/
COPY .env /app/

RUN yarn
RUN yarn build


FROM nginx:alpine
COPY --from=build-stage /app/.env .
COPY --from=build-stage /app/dist /usr/share/nginx/html
