/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/pages/*.html"],
  theme: {
    extend: {
      colors: {
        'esn-red': '#C41230',
      }
    },
  },
  safelist: [
    'grid',
    'bg-gray-300',
    'rounded-lg',
    'dark:bg-grey-100',
    'w-4/5', 
    'h-auto', 
    'ml-auto', 
    'mr-auto', 
    'mb-4', 
    'mt-4',
    'text-xs',
    'justify-items-start',
    'justify-items-end',
    'fixed',
    'inset-0', 
    'bg-gray-500', 
    'bg-opacity-75',
    'transition-opacity',
    'p-0', 
    'm-auto', 
    'w-3/5', 
    'h-2/5', 
    'overflow-auto', 
    'rounded-lg', 
    'bg-gray-300', 
    'bg-opacity-100', 
    'border-2',
    'flex',
    'flex-col',
    'justify-center', 
    'w-screen', 
    'h-screen',
    'grid', 
    'h-[5%]',
    'w-screen', 
    'h-1/12',
    'justify-items-center',
    'ml-1',
    'mr-1',
    'float-left',
    'float-right',
    'absolute',
    'left-5',
    'top-5',
    'z-50',
    'w-8',
    'h-8',
    'stroke-black',
    'dark:stroke-white'
  ],
  plugins: [],
}