version: '3.9'
services:
  esn-db:
    container_name: esn-db
    image: mysql:latest
    restart: always
    networks:
      - esn-backend
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 's23-esn-s2023'
      MYSQL_DATABASE: 'fse'
      MYSQL_USER: 'esnbackend'
      MYSQL_PASSWORD: 's23-esn-s2023'
  esn-api:
    container_name: esn-api
    image: jyang285/esn-api:latest
    environment:
      - DB_HOST=esn-db
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - esn-db
    restart: always
    networks:
      - esn-frontend
      - esn-backend
  esn-web:
    container_name: esn-web
    image: jyang285/esn-web:latest
    restart: always
    networks:
      - esn-frontend
    depends_on:
      - esn-api
    ports:
      - 2333:80
networks:
  esn-frontend:
    driver: bridge
  esn-backend:
    driver: bridge