version: '3.9'
services:
  db:
    container_name: esn-db
    image: mysql:latest
    restart: always
    networks:
      - esn
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 's23-esn-s2023'
      MYSQL_DATABASE: 'fse'
      MYSQL_USER: 'esnbackend'
      MYSQL_PASSWORD: 's23-esn-s2023'
  redis:
    container_name: esn-redis
    image: redis:alpine
    networks:
      - esn
    ports:
      - 6379:6379
    restart: always
  api:
    container_name: esn-api
    image: esn-api
    environment:
      - DB_HOST=esn-db
      - REDIS_HOST=esn-redis
    build:
      context: ./backend
      dockerfile: Dockerfile-api
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    restart: always
    networks:
      - esn
  web:
    container_name: esn-web
    image: esn-web
    build:
      context: ./frontend
      dockerfile: Dockerfile-web
    restart: always
    networks:
      - esn
    depends_on:
      - api
    ports:
      - 2333:80
networks:
  esn:
    driver: bridge
