FROM node:18 AS build-stage
WORKDIR /app
COPY . ./
RUN yarn --silent
RUN yarn build

FROM node:18-slim
WORKDIR /app
COPY --from=build-stage /app/dist ./dist
COPY --from=build-stage /app/.env ./
COPY --from=build-stage /app/.pnp.cjs ./
COPY --from=build-stage /app/.yarn/cache/ .yarn/cache/
COPY --from=build-stage /app/.yarn/releases/ .yarn/releases/
COPY --from=build-stage /app/.yarn/unplugged/ .yarn/unplugged/

EXPOSE 3000
CMD ["node", "-r", "./.pnp.cjs", "./dist/index.js"]

