FROM node:18 AS build-stage
WORKDIR /app
COPY . ./
RUN npm install -f
RUN npm run build

FROM gcr.io/distroless/nodejs18-debian11
WORKDIR /app
COPY --from=build-stage /app/node_modules ./node_modules
COPY --from=build-stage /app/dist ./dist
COPY --from=build-stage /app/.env.prod .
EXPOSE 3000
CMD ["dist/index.js", "--mode", "prod"]

