export enum Role {
    ADMIN,
    COORDINATOR,
    CITIZEN,
  }

  export enum Status {
    UNDEFINED,
    OK,
    HELP,
    EMERGENCY,
  }
  
  export enum OnlineStatus {
    ONLINE,
    OFFLINE,
  }
  
  export enum Context {
    UNKNOWN,
    CITIZENNAME,
    CITIZENSTATUS,
    PUBLICCHAT,
    PRIVATECHAT
  }

  export enum StatusCode {
    BADREQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOTFOUND = 404,
    DUPLICATE = 409,
}

export enum ErrorMessage {
    DEFAULTERROR = 'Default error',
    AUTHNOHEADER = 'Error generated by auth middleware: Header not found.',
    AUTHWRONGHEADER = 'Error generated by auth middleware: Header malformed.',
    AUTHUNAUTHORIZED = 'Error generated by auth middleware: Token wrong or expired, unauthorized.',
    BADUSERNAMEREQ = 'Error generated by service: Username not follow the rule, please provide another username.',
    BADPASSWORDREQ = 'Error generated by service: Password not follow the rule, please provide another password.',
    WRONGUSERNAME = 'Error generated by service: User does not exist.',
    WRONGPASSWORD = 'Error generated by service: Password wrong, please check the password.',
    DUPLICATEUSER = 'Error generated by DB query: Username already exists, please change a username.',
    FORBIDDENUPDATEUSER = 'Error generated by role permission: No permission to update user profile.',
    EMPTYMESSAGE = 'Error generated by service: Message cannot be empty or only space.',
    ROOMIDNOTFOUND = 'Error generated by service: Room ID cannot be found.'
}
