name: Docker Build CI

on:
  push:
    branches: [ "main" ]
jobs:

  build:

    runs-on: self-hosted
    steps:
      - name: Upgrade User Permission
        uses: ./
        with:
          command: chown -R $USER:$USER /home/$USER/actions-runner/_work/s23-ESN-SB1/
      - uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: backend
          file: backend/Dockerfile-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/esn-api:latest
      -
        name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: frontend
          file: frontend/Dockerfile-web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/esn-web:latest
