name: Sigrid pull request feedback
on: [pull_request]

jobs:
  sigridci:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@main
        with:
          customer: Cmusvfse
          system: S23-esn-sb1
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID }}"
