name: sigrid-pr
on: [pull_request]

jobs:
  sigridci:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Download Sigrid CI
        run: "git clone https://github.com/Software-Improvement-Group/sigridci.git sigridci"
      - name: "Run Sigrid CI" 
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID }}"
        run: "./sigridci/sigridci/sigridci.py --customer Cmusvfse --system S23-esn-sb1 --source . --exclude backend/.yarn --exclude frontend/.yarn --publish"
